var VOICE_COMMANDER_EVENT_CODE = {
		OpenUrl: 0,
		Click: 1,
		Change: 2,
		Comment: 3,
		Submit: 4,
		CheckPageTitle: 5,
		CheckPageLocation: 6,
		CheckTextPresent: 7,
		CheckValue: 8,
		CheckValueContains: 9,
		CheckText: 10,
		CheckHref: 11,
		CheckEnabled: 12,
		CheckDisabled: 13,
		CheckSelectValue: 14,
		CheckSelectOptions: 15,
		CheckImageSrc: 16,
		PageLoad: 17,
		ScreenShot: 18,
		MouseDown: 19,
		MouseUp: 20,
		MouseDrag: 21,
		MouseDrop: 22,
		KeyPress: 23,
		ReadElement: 24,
		ClickWhen: 25,
		SetVarValue: 26,
		RequestVarValue: 27,
		ShowElement: 28,
		RequestInput: 29,
		RequestClick: 30
	},
	VOICE_COMMANDER_BUTTON_CODE = {
		LeftButton: 0,
		MiddleButton: 1,
		RightButton: 2,
		UnknownButton: 3
	};
